version: '3.8'

services:
  apache:
    build: ./apache
    ports:
      - "8443:443"
    depends_on:
      - flaskapp

  flaskapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
